### Steps
```
1. Preprocessing And Cleaning
2. Train Test Split
3. BOW And TF-IDF (Sentences--->vectors) (Preventing Data Leakage)
4. Train the Models
```

In [26]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','messages'])

In [11]:
df.shape

(5572, 2)

In [12]:
df.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Data Cleaning and Preprocessing

In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [10]:
stop_words=set(stopwords.words('english'))

In [7]:
lemma=WordNetLemmatizer()

In [13]:
corpus=[]
for i in range(len(df)):
    review=re.sub('[^a-zA-z]',' ',df['messages'][i]).lower().split()
    corpus.append(' '.join([lemma.lemmatize(word) for word in review if word not in stop_words]))

In [14]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [42]:
y=df['label'].replace({'spam':1,'ham':0})
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64

In [43]:
y.unique()

array([0, 1], dtype=int64)

In [63]:
len(corpus),len(y)

(5572, 5572)

### Train Test Split

In [73]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(corpus,y,test_size=.20,random_state=42)

In [74]:
len(xtrain),len(xtest)

(4457, 1115)

# Bag Of Words

In [75]:
from sklearn.feature_extraction.text import CountVectorizer

In [76]:
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [77]:
xtrain

['reply win weekly fifa world cup held send stop end service',
 'hello sort town already dont rush home eating nacho let know eta',
 'come guoyang go n tell u told',
 'hey sathya till dint meet even single time saw situation sathya',
 'orange brings ringtones time chart hero free hit week go ringtones pic wap stop receiving tip reply stop',
 'sitting mu waiting everyone get suite take shower',
 'finish liao u',
 'urgent mobile awarded bonus caller prize nd attempt contact call box qu',
 'probably still going stuff',
 'wah lucky man save money hee',
 'hey u still gym',
 'oh lk tt den take e one tt end cine lor dun wan yogasana oso',
 'ok lor',
 'still havent collected dough pls let know go place sent get control number',
 'stupid possible',
 'u secret admirer reveal think u r special call opt reply reveal stop per msg recd cust care',
 'amazing rearrange letter give meaning dormitory dirty room astronomer moon starer eye see election result lie let recount mother law woman hitler eleven

In [78]:
x_train=cv.fit_transform(xtrain).toarray()
x_test=cv.transform(xtest).toarray()

To prevent data leakage
* xtrain -----> fit_transform
* xtest ------> transfrom 

In [79]:
x_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [80]:
cv.vocabulary_

{'reply': 1721,
 'win': 2398,
 'weekly': 2373,
 'world': 2433,
 'cup': 446,
 'send': 1825,
 'stop': 1990,
 'end': 580,
 'service': 1839,
 'send stop': 1830,
 'stop end': 1992,
 'hello': 902,
 'sort': 1942,
 'town': 2179,
 'already': 45,
 'dont': 532,
 'rush': 1767,
 'home': 936,
 'eating': 568,
 'let': 1134,
 'know': 1077,
 'let know': 1136,
 'come': 376,
 'go': 785,
 'tell': 2067,
 'told': 2155,
 'hey': 905,
 'till': 2133,
 'dint': 515,
 'meet': 1275,
 'even': 609,
 'single': 1882,
 'time': 2134,
 'saw': 1786,
 'situation': 1890,
 'orange': 1497,
 'brings': 211,
 'ringtones': 1750,
 'free': 702,
 'hit': 917,
 'week': 2366,
 'pic': 1557,
 'wap': 2342,
 'receiving': 1700,
 'reply stop': 1726,
 'sitting': 1889,
 'mu': 1370,
 'waiting': 2320,
 'everyone': 618,
 'get': 756,
 'suite': 2017,
 'take': 2044,
 'shower': 1866,
 'finish': 675,
 'liao': 1138,
 'urgent': 2270,
 'mobile': 1325,
 'awarded': 117,
 'bonus': 184,
 'caller': 260,
 'prize': 1637,
 'nd': 1393,
 'attempt': 103,
 'contact': 

# Model Building

In [81]:
from sklearn.naive_bayes import MultinomialNB

In [83]:
bow_model=MultinomialNB().fit(x_train,ytrain)

In [84]:
y_pred=bow_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [85]:
from sklearn.metrics import accuracy_score,classification_report

In [86]:
accuracy_score(ytest,y_pred)

0.9847533632286996

In [87]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.95      0.94      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115



# TF-IDF

In [92]:
xtrain,xtest,ytrain,ytest=train_test_split(corpus,y,test_size=.20,random_state=42)

In [93]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [94]:
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [95]:
x_train=tv.fit_transform(xtrain).toarray()
x_test=tv.transform(xtest).toarray()

In [96]:
tv.vocabulary_

{'reply': 1721,
 'win': 2398,
 'weekly': 2373,
 'world': 2433,
 'cup': 446,
 'send': 1825,
 'stop': 1990,
 'end': 580,
 'service': 1839,
 'send stop': 1830,
 'stop end': 1992,
 'hello': 902,
 'sort': 1942,
 'town': 2179,
 'already': 45,
 'dont': 532,
 'rush': 1767,
 'home': 936,
 'eating': 568,
 'let': 1134,
 'know': 1077,
 'let know': 1136,
 'come': 376,
 'go': 785,
 'tell': 2067,
 'told': 2155,
 'hey': 905,
 'till': 2133,
 'dint': 515,
 'meet': 1275,
 'even': 609,
 'single': 1882,
 'time': 2134,
 'saw': 1786,
 'situation': 1890,
 'orange': 1497,
 'brings': 211,
 'ringtones': 1750,
 'free': 702,
 'hit': 917,
 'week': 2366,
 'pic': 1557,
 'wap': 2342,
 'receiving': 1700,
 'reply stop': 1726,
 'sitting': 1889,
 'mu': 1370,
 'waiting': 2320,
 'everyone': 618,
 'get': 756,
 'suite': 2017,
 'take': 2044,
 'shower': 1866,
 'finish': 675,
 'liao': 1138,
 'urgent': 2270,
 'mobile': 1325,
 'awarded': 117,
 'bonus': 184,
 'caller': 260,
 'prize': 1637,
 'nd': 1393,
 'attempt': 103,
 'contact': 

# Model Building

In [98]:
tfidf_model=MultinomialNB().fit(x_train,ytrain)

In [99]:
y_pred=tfidf_model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [100]:
accuracy_score(ytest,y_pred)

0.9811659192825112

In [101]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       0.98      0.87      0.93       149

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



# Word2Vec

In [189]:
import gensim
from gensim.models import Word2Vec,KeyedVectors
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [234]:
words = [simple_preprocess(sent) for sent in corpus]

In [235]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

# Training Word2Vec from scratch

In [236]:
model = Word2Vec(vector_size=100, window=5, min_count=5)

In [237]:
model.build_vocab(words)

In [238]:
model.train(words, total_examples=model.corpus_count, epochs=model.epochs)

(174196, 237835)

In [240]:
# To get all the vocabulary
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'day',
 'ok',
 'free',
 'know',
 'come',
 'like',
 'time',
 'good',
 'got',
 'love',
 'text',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'please',
 'later',
 'pls',
 'co',
 'msg',
 'min',
 'dear',
 'night',
 'make',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'claim',
 'hope',
 'great',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'wat',
 'work',
 'way',
 'yes',
 'www',
 'prize',
 'let',
 'right',
 'tomorrow',
 'already',
 'tone',
 'ask',
 'said',
 'win',
 'cash',
 'amp',
 'life',
 'yeah',
 'im',
 'really',
 'meet',
 'babe',
 'find',
 'miss',
 'morning',
 'last',
 'year',
 'service',
 'uk',
 'thanks',
 'care',
 'anything',
 'would',
 'com',
 'also',
 'nokia',
 'lol',
 'feel',
 'every',
 'keep',
 'pick',
 'sure',
 'urgent',
 'sent',
 'contact',


In [241]:
# vocabulary size
model.corpus_count

5572

In [242]:
model.wv.similar_by_word('good')

[('day', 0.9995898008346558),
 ('give', 0.9995892643928528),
 ('much', 0.9995872974395752),
 ('get', 0.9995838403701782),
 ('going', 0.9995783567428589),
 ('today', 0.9995691180229187),
 ('said', 0.9995672702789307),
 ('last', 0.9995658993721008),
 ('go', 0.9995636940002441),
 ('like', 0.9995612502098083)]

In [243]:
def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if not vectors:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

In [244]:
X=[]
for i in range(len(words)):
    X.append(avg_word2vec(words[i]))

In [245]:
X

[array([-0.101, 0.266, -0.00742, 0.0486, 0.0656, -0.443, 0.0488, 0.506, -0.182, -0.149, -0.155, -0.301, -0.0767, 0.0702, 0.0613, -0.217, 0.0114, -0.229, 0.0675, -0.436, 0.16, 0.141, 0.0173, -0.138, -0.115, -0.00413, -0.312, -0.296, -0.184, 0.0203, 0.285, -0.0233, 0.106, -0.0926, -0.114, 0.317, -0.0954, -0.336, -0.181, -0.476, -0.0112, -0.207, 0.0509, 0.0335, 0.153, -0.041, -0.12, -0.0565, 0.169, 0.194, 0.138, -0.139, -0.0477, 0.0266, -0.133, 0.0642, 0.165, 0.0393, -0.221, 0.0559, 0.0879, 0.151, -0.13, -0.101, -0.255, 0.18, 0.0461, 0.144, -0.33, 0.287, -0.23, 0.11, 0.259, -0.0862, 0.275, 0.157, 0.0081, -0.014, -0.242, 0.0801, -0.115, -0.069, -0.231, 0.372, -0.0396, 0.149, -0.0125, 0.339, 0.316, 0.127, 0.35, 0.119, -0.0302, 0.0119, 0.403, 0.256, 0.0328, -0.326, 0.12, -0.0276], dtype=float32),
 array([-0.0837, 0.223, -0.00298, 0.0481, 0.053, -0.376, 0.0401, 0.427, -0.152, -0.126, -0.13, -0.256, -0.0593, 0.0548, 0.0485, -0.181, 0.0156, -0.193, 0.0527, -0.374, 0.133, 0.122, 0.0115, -0.123, 

In [246]:
len(X)

5572

In [247]:
X=pd.DataFrame(X)

In [248]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=.20,random_state=42)

In [249]:
from sklearn.ensemble import RandomForestClassifier

In [250]:
rf=RandomForestClassifier()

In [251]:
rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [252]:
ypred=rf.predict(xtest)

In [253]:
from sklearn.metrics import accuracy_score,classification_report

In [254]:
accuracy_score(ytest,ypred)

0.9704035874439462

In [255]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       966
           1       0.97      0.81      0.88       149

    accuracy                           0.97      1115
   macro avg       0.97      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115

